name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: convert md to pdf
        uses: docker://pandoc/latex:2.9
        with:
          entrypoint: /bin/sh
          args: -c "cd docs/PTA题解; for f in PTA*.md; do pandoc $f -o ${f%.xls}.pdf --pdf-engine=xelatex -V documentclass=ctexart; done"

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
